import { useAuth } from "@/_core/hooks/useAuth";
import Navbar from "@/components/Navbar";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";
import { ArrowUp, CalendarDays, Crown, Loader2, Medal, Send, Trophy } from "lucide-react";
import { useState } from "react";
import { useParams } from "wouter";
import { toast } from "sonner";

export default function CompetitionDetail() {
  const { id } = useParams<{ id: string }>();
  const competitionId = Number(id);
  const { user, isAuthenticated } = useAuth();
  const [contentType, setContentType] = useState<"video" | "post">("video");
  const [contentId, setContentId] = useState("");
  const [caption, setCaption] = useState("");
  const [announcement, setAnnouncement] = useState("");
  const { data: competition, isLoading } = trpc.competition.getById.useQuery({ competitionId }, { enabled: Number.isFinite(competitionId) });
  const { data: userVideos } = trpc.video.getUserVideos.useQuery({ userId: user?.id ?? 0, limit: 50, offset: 0 }, { enabled: Boolean(user?.id) });
  const { data: userPosts } = trpc.post.byUser.useQuery({ userId: user?.id ?? 0 }, { enabled: Boolean(user?.id) });
  const utils = trpc.useUtils();
  const join = trpc.competition.join.useMutation({ onSuccess: async () => { toast.success("تم تسجيل مشاركتك في المسابقة"); setContentId(""); await utils.competition.getById.invalidate({ competitionId }); }, onError: error => toast.error(error.message) });
  const vote = trpc.competition.vote.useMutation({ onSuccess: async () => { await utils.competition.getById.invalidate({ competitionId }); }, onError: error => toast.error(error.message) });
  const announce = trpc.competition.announce.useMutation({ onSuccess: data => { setAnnouncement(""); toast.success(`تم إرسال التنبيه إلى ${data.notifiedCount} مشارك`); }, onError: error => toast.error(error.message) });
  const declareWinner = trpc.competition.declareWinner.useMutation({ onSuccess: async data => { toast.success(data?.alreadyAwarded ? "سبق منح الجائزة للفائز" : "تم إعلان الفائز ومنح الجائزة"); await utils.competition.getById.invalidate({ competitionId }); }, onError: error => toast.error(error.message) });

  if (isLoading) return <div className="min-h-screen bg-background"><Navbar /><div className="flex justify-center py-28"><Loader2 className="animate-spin text-primary" /></div></div>;
  if (!competition) return <div className="min-h-screen bg-background"><Navbar /><p className="text-center py-28 text-muted-foreground">المسابقة غير موجودة.</p></div>;
  const isOpen = competition.status === "active";

  return <div className="min-h-screen bg-background pb-20"><Navbar /><main className="container max-w-4xl py-8"><Card className="p-7 md:p-9 bg-gradient-to-br from-accent/15 via-card to-primary/10 border-accent/20 mb-6"><div className="flex items-start justify-between gap-4"><div><span className="inline-flex items-center gap-1 rounded-full bg-accent/10 text-accent px-3 py-1 text-sm"><Trophy className="w-4 h-4" /> {isOpen ? "المسابقة مفتوحة" : competition.status === "upcoming" ? "قريبًا" : "انتهت المسابقة"}</span><h1 className="text-3xl font-bold mt-4">{competition.title}</h1><p className="text-muted-foreground mt-3 leading-7">{competition.description ?? `مسابقة في فئة ${competition.category}`}</p></div><div className="text-left shrink-0"><p className="text-xs text-muted-foreground flex items-center gap-1"><CalendarDays className="w-3 h-3" /> تنتهي</p><p className="font-semibold mt-1">{new Date(competition.endsAt).toLocaleDateString("ar-EG")}</p></div></div><div className="grid sm:grid-cols-2 gap-3 mt-6"><div className="rounded-2xl bg-background/45 p-4"><p className="text-xs text-muted-foreground">الجائزة الرمزية</p><p className="font-bold flex items-center gap-2 mt-2"><Crown className="w-5 h-5 text-accent" /> {competition.prizeTitle}</p></div><div className="rounded-2xl bg-background/45 p-4"><p className="text-xs text-muted-foreground">نقاط الفائز</p><p className="font-bold text-primary mt-2">+{competition.prizePoints} نقطة</p></div></div></Card>
  {isAuthenticated && isOpen && <Card className="p-5 bg-card/70 border-border/70 mb-6"><h2 className="font-bold mb-4">شارك بمحتواك</h2><div className="flex gap-2 mb-3"><Button size="sm" variant={contentType === "video" ? "default" : "outline"} onClick={() => setContentType("video")}>فيديو</Button><Button size="sm" variant={contentType === "post" ? "default" : "outline"} onClick={() => setContentType("post")}>منشور</Button></div><div className="grid md:grid-cols-[1fr_1.3fr] gap-3"><select value={contentId} onChange={event => setContentId(event.target.value)} className="rounded-xl border border-border bg-input px-3"><option value="">اختر {contentType === "video" ? "فيديو" : "منشورًا"}</option>{contentType === "video" ? userVideos?.map(video => <option key={video.id} value={video.id}>{video.title}</option>) : userPosts?.map(post => <option key={post.id} value={post.id}>منشور #{post.id}</option>)}</select><input value={caption} onChange={event => setCaption(event.target.value.slice(0, 280))} placeholder="تعليق قصير (اختياري)" className="rounded-xl border border-border bg-input px-3" /></div><Button className="mt-3 gap-2" disabled={!contentId || join.isPending} onClick={() => join.mutate({ competitionId, ...(contentType === "video" ? { videoId: Number(contentId) } : { postId: Number(contentId) }), caption: caption || undefined })}>{join.isPending ? <Loader2 className="w-4 h-4 animate-spin" /> : <Send className="w-4 h-4" />} دخول المسابقة</Button></Card>}
  {user?.role === "admin" && <Card className="p-5 bg-primary/5 border-primary/20 mb-6"><h2 className="font-bold mb-3">إدارة إشعارات المسابقة</h2><div className="flex flex-col md:flex-row gap-3"><input value={announcement} onChange={event => setAnnouncement(event.target.value.slice(0, 500))} placeholder="اكتب تحديثًا يصل إلى جميع المشاركين..." className="h-10 flex-1 rounded-xl border border-border bg-input px-3" /><Button variant="outline" disabled={announcement.trim().length < 3 || announce.isPending} onClick={() => announce.mutate({ competitionId, message: announcement.trim() })}>{announce.isPending ? <Loader2 className="w-4 h-4 animate-spin" /> : "إرسال تنبيه"}</Button><Button className="gap-2" disabled={declareWinner.isPending || competition.status === "completed"} onClick={() => declareWinner.mutate({ competitionId })}>{declareWinner.isPending ? <Loader2 className="w-4 h-4 animate-spin" /> : <Trophy className="w-4 h-4" />} إعلان الفائز</Button></div></Card>}
  <section><div className="flex items-center justify-between mb-4"><div><h2 className="text-xl font-bold">مشاركات المتسابقين</h2><p className="text-sm text-muted-foreground">صوّت للمحتوى الذي يستحق الفوز.</p></div><span className="inline-flex items-center gap-1 text-sm text-muted-foreground"><Medal className="w-4 h-4 text-accent" /> {competition.entries.length} مشاركة</span></div><div className="grid md:grid-cols-2 gap-4">{competition.entries.map((entry, index) => <Card key={entry.id} className="p-5 bg-card/70 border-border/70"><div className="flex items-center justify-between mb-4"><span className="inline-flex items-center gap-2 font-semibold text-sm"><span className="w-7 h-7 rounded-full bg-accent/15 text-accent flex items-center justify-center">{index + 1}</span> مشاركة</span><Button variant="ghost" size="sm" className="gap-1 text-accent" disabled={!isAuthenticated || vote.isPending || !isOpen} onClick={() => vote.mutate({ entryId: entry.id })}><ArrowUp className="w-4 h-4" /> {entry.votes}</Button></div><p className="text-sm text-muted-foreground mb-3">{entry.caption ?? "مشاركة في المسابقة"}</p>{entry.video ? <video src={entry.video.videoUrl} poster={entry.video.thumbnailUrl ?? undefined} controls preload="metadata" className="max-h-72 w-full rounded-xl bg-black" /> : entry.post ? <div className="space-y-2">{entry.post.blocks.slice(0, 3).map(block => block.blockType === "text" ? <p key={block.id} className="whitespace-pre-line text-sm leading-6">{block.textContent}</p> : block.blockType === "image" ? <img key={block.id} src={block.mediaUrl ?? ""} alt="مشاركة" className="max-h-60 w-full object-contain rounded-xl" loading="lazy" /> : <video key={block.id} src={block.mediaUrl ?? ""} controls preload="metadata" className="max-h-60 w-full rounded-xl bg-black" />)}</div> : null}</Card>)}</div>{competition.rewards.length > 0 && <Card className="p-5 mt-6 bg-accent/5 border-accent/20"><h3 className="font-bold flex items-center gap-2"><Crown className="w-5 h-5 text-accent" /> الفائزون والجوائز</h3><div className="mt-4 space-y-3">{competition.rewards.map(reward => <div key={reward.id} className="flex items-center justify-between text-sm"><span>{reward.title}</span><span className="text-primary">+{reward.pointsAwarded} نقطة</span></div>)}</div></Card>}</section></main></div>;
}
