import { useAuth } from "@/_core/hooks/useAuth";
import Navbar from "@/components/Navbar";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";
import { CalendarDays, Crown, Loader2, Medal, Plus, Sparkles, Trophy } from "lucide-react";
import { Link } from "wouter";
import { useState } from "react";

const statusLabels = { active: "مفتوحة", upcoming: "قريبًا", completed: "منتهية" } as const;

export default function Competitions() {
  const { user } = useAuth();
  const [status, setStatus] = useState<"upcoming" | "active" | "completed" | undefined>(undefined);
  const { data: items, isLoading } = trpc.competition.list.useQuery(status ? { status } : undefined);
  return <div className="min-h-screen bg-background pb-20"><Navbar /><main className="container py-8"><section className="rounded-3xl border border-accent/20 bg-gradient-to-br from-accent/15 via-card to-primary/10 p-7 md:p-9 mb-7"><div className="flex items-start justify-between gap-4"><div className="flex items-start gap-4"><div className="w-13 h-13 rounded-2xl bg-accent/20 flex items-center justify-center"><Trophy className="w-7 h-7 text-accent" /></div><div><p className="text-sm text-accent font-semibold">تنافس واصنع أثرًا</p><h1 className="text-3xl font-bold mt-1">مسابقات الترند</h1><p className="text-muted-foreground mt-2 max-w-2xl">ادخل بمحتواك، اجمع أصوات المجتمع، واربح جائزة رمزية وشارة ونقاطًا تظهر في إنجازاتك.</p></div></div>{user?.role === "admin" && <Link href="/competitions/new"><Button className="gap-2"><Plus className="w-4 h-4" /> إنشاء مسابقة</Button></Link>}</div></section><div className="flex flex-wrap gap-2 mb-6">{([undefined, "active", "upcoming", "completed"] as const).map(item => <Button key={item ?? "all"} size="sm" variant={status === item ? "default" : "outline"} onClick={() => setStatus(item)}>{item === undefined ? "كل المسابقات" : statusLabels[item]}</Button>)}</div>{isLoading ? <div className="flex justify-center py-28"><Loader2 className="animate-spin text-primary" /></div> : !items?.length ? <Card className="p-12 text-center bg-card/70"><Medal className="w-12 h-12 text-accent mx-auto mb-4" /><h2 className="text-xl font-bold">لا توجد مسابقات في هذا القسم</h2><p className="text-muted-foreground mt-2">تابع هذه الصفحة لمعرفة موعد المسابقة القادمة.</p></Card> : <div className="grid md:grid-cols-2 xl:grid-cols-3 gap-5">{items.map(item => <Card key={item.id} className="p-5 bg-card/70 border-border/70 hover:border-accent/50 transition-colors"><div className="flex justify-between items-center mb-4"><span className="inline-flex rounded-full bg-accent/10 text-accent px-3 py-1 text-xs"><Sparkles className="w-3 h-3 ml-1" /> {statusLabels[item.status]}</span><span className="text-xs text-muted-foreground flex items-center gap-1"><CalendarDays className="w-3 h-3" /> {new Date(item.endsAt).toLocaleDateString("ar-EG")}</span></div><h2 className="font-bold text-xl mb-2">{item.title}</h2><p className="text-sm text-muted-foreground leading-6 min-h-12">{item.description ?? `مسابقة ضمن فئة ${item.category}`}</p><div className="mt-4 rounded-xl bg-secondary/40 p-3"><p className="text-xs text-muted-foreground">الجائزة الرمزية</p><p className="font-semibold flex items-center gap-2 mt-1"><Crown className="w-4 h-4 text-accent" /> {item.prizeTitle} <span className="mr-auto text-sm text-primary">+{item.prizePoints} نقطة</span></p></div><Link href={`/competitions/${item.id}`}><Button className="w-full mt-4" variant="outline">عرض المسابقة</Button></Link></Card>)}</div>}</main></div>;
}
